version: "3"

services:
  backend:
    build: ./back
    volumes:
      - ./back/:/back # maps host diretory to internal container directory
    working_dir: /back/
    command: sh run.sh
  frontend:
    image: node:latest
    command: sh build.sh
    working_dir: /frontend
    volumes:
      - ./front/eventos/:/frontend
  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./front/eventos/build:/var/www/front
      - ./back/:/back
    depends_on:
      - backend